Base Header Level: 2
latex input: metadata
latex author: Ryan Thomas Munz
latex title: Title (TODO)
bibtex: MThesis_bib
myyear: 2016
myreporttype: Masters Thesis
mydegree: Masters
mydepartment: Science
latex input: vtthesis/setup.tex
latex footer: vtthesis/footer.tex

# Introduction
{{./Chapters/Munz_Chapter_1.mmd}}
# Edge Detection Litterature Review
{{./Chapters/Munz_Chapter_2.mmd}}
# Optical Flow and The Canny Edge Detector
{{./Chapters/Munz_Chapter_3.mmd}}
# Results
{{./Chapters/Munz_Chapter_4.mmd}}
# Conclusions and Future Work
{{./Chapters/Munz_Chapter_5.mmd}}
