Base Header Level: 2
latex input: metadata
latex author: Ryan Thomas Munz
latex title: Title (TODO)
bibtex: MThesis_bib
myreporttype: Masters Thesis
mydegree: Masters
mydepartment: Mechanical Engineering
latex input: vtthesis/setup.tex
latex footer: vtthesis/footer.tex

{{./Chapters/Munz_Chapter_1.mmd}}

{{./Chapters/Munz_Chapter_2.mmd}}

{{./Chapters/Munz_Chapter_3.mmd}}

{{./Chapters/Munz_Chapter_4.mmd}}

{{./Chapters/Munz_Chapter_5.mmd}}
