## Theory

How each part works in detail
Theory behind the parts
Summarize Ch 2 and 3 together

### Edge Detection


### Shape Segmentation


### Color Segmentation

#### Color Spaces

YUV color space [Miura]

RGB

L*a*b

HSV



### Optical Flow


### Summary

**(TODO)**: Summarize how the parts fit together in the overall process of detection and recognition.