## Theory

How each part works in detail
Theory behind the parts
Summarize Ch 2 and 3 together

### Convolution


### Kalman Filter


### Edge Detection


### Shape Segmentation


### Color Segmentation

#### Color Spaces

In the previous chapter, many different color spaces were mentioned. This section goes into mor detail on how the color spaces are similar and different from one another.

YUV color space [Miura]

RGB

L*a*b [Siogkas]

HSV

HSI

### Optical Flow


### Summary

**(TODO)**: Summarize how the parts fit together in the overall process of detection and recognition.