## Introduction

### Background
	Why do we care?

## Background

Talk about the history of edge detection and 

## Applications that benefit from better edge detection


## Current Challenges
Background on why we care about canny edge dection and its applications.

The reason why we want to be able to detect and recognize road signs in real time is that they are designed to be easily recognizable by humans and give us important information as we drive, so why should autonomous vehicles not use the signs for the same reason? [Md. Safaet Hossain and Zakir Hyder], [Mehdi Fartaj and Sedigheh Ghofrani]



However color information is sensitive to the change of weather or lighting condition and, therefore, it is some-time difficult to extract traffic signs reliably only by color. [Miura]


Nevertheless, a number of challenges remain for a success-
ful recognition. First, weather and lighting conditions vary sig- nificantly in traffic environments, diminishing the advantage of the above claimed object uniqueness. Additionally, as the cam- era is moving, additional image distortions, such as, motion blur and abrupt contrast changes, occur frequently. Further, the sign installation and surface material can physically change over time, influenced by accidents and weather, hence resulting in rotated signs and degenerated colors. Finally, the constraints given by the area of application require inexpensive systems (i.e., low-quality sensor, slow hardware), high accuracy and real-time computation. [Bahlmann]


## Thesis Problem Statement

## Thesis Overview

### Chapter 2


### Chapter 3


### Chapter 4


### Chapter 5

