## Optical Flow
Optical flow is 

### Dense Optical Flow


### Sparse Optical Flow


-Talk about optical flow

## Using Optical Flow on a Canny Image


-Talk about combining Canny and Optical flow

## Canny Algorithm to be Used
-Present my “Tuned” Canny algorithm

## Experiments Conducted


-Talk about experiments
