## Introduction

### Background
	Why do we care?

## Background

Talk about the history of edge detection and 

## Applications that benefit from better edge detection

Background on why we care about canny edge dection and its applications.

The reason why we want to be able to detect and recognize road signs in real time is that they are designed to be easily recognizable by humans and give us important information as we drive, so why should autonomous vehicles not use the signs for the same reason? [Md. Safaet Hossain and Zakir Hyder], [Mehdi Fartaj and Sedigheh Ghofrani]

## Thesis Problem Statement

## Thesis Overview

### Chapter 2


### Chapter 3


### Chapter 4


### Chapter 5

