## Results and Discussion

Present what I will use
Results from my tests

### The System Used

**(TODO)**: Talk about Canny edge dection, what programing language/IDE used, optical flow, and databases that I am using. Basically everything I am using for my thesis and the order in which information flows.

### Test Results from the System

#### (Stock) Canny Edge Detection Only Results

#### Canny Edge Detection with Adaptive Thresholding

#### Canny Edge Detection with Optical flow

#### Combining All

#### Results using different flow directions